import './globals.css'
import { Inter } from 'next/font/google'
import ButtonWhatsApp from '@/components/button/ButtonWhatsApp'
import AuthContext from '@/contexts/AuthContext'
import { Portal } from '@/components/portal/Portal'
import Spinner from '@/components/spinner'
import Navbar from '@/components/navbar/Navbar'
import BannerTop from '@/components/banner/BannerTop'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function Content({ children }) {
  return (
    <>
      <header className="bg-slate-50">
        <BannerTop />
        <Navbar />
      </header>
      <main className="min-h-screen bg-white">
        {children}
        <Portal>
          <Spinner />
        </Portal>
      </main>
      <footer className="bg-slate-50">
        <ButtonWhatsApp />
        <div id="portal"></div>
      </footer>
    </>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <Content>{children}</Content>
        </AuthContext>
      </body>
    </html>
  )
}
